config {
    type: "view",
    name: "available_bicycles_dataform"
}

-- Reads data from available_bicycles table and creates the available_bicycles_dataform view
SELECT
  ab.bicycle_id,
  ab.manufacturer,
  ab.color,
  ab.datos
FROM
  `ark-learn-project.bicycles.available_bicycles` AS ab
LEFT JOIN
  `ark-learn-project.bicycles_scheduled.scheduled_job_used_bicycles` AS abdf
ON
  ab.bicycle_id = abdf.bike_id
WHERE
  abdf.bike_id IS NULL
