config {
    type: "incremental",
    name: "used_bicycles",
    dependencies: ["available_bicycles_dataform"]
}

SELECT
  bicycle_id AS bike_id,
  manufacturer,
  current_date AS creation_date,
  CAST(NULL AS json) AS DATA,
  color,
  datos,
  CURRENT_DATETIME() AS creation_date_time,
  JSON_VALUE(datos, '$.key1') AS key_1,
  JSON_VALUE(datos.nested, '$.nested_key1') AS nested_key_1
FROM
  ${ref("available_bicycles_dataform")}
WHERE
  bicycle_id IS NOT NULL
